CREATE TABLE CHALLENGE_4(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	VALOR INT NOT NULL
)
--
INSERT INTO CHALLENGE_4(VALOR) VALUES (4),(11),(57),(24),(47)
--
SELECT	CASE
			WHEN VALOR%2=0 THEN 'PAR'
			ELSE 'IMPAR'
			END AS 'CHALLENGE 4'
FROM CHALLENGE_4

--SE UTILIZA EL OPERADOR MÓDULO(%) PARA COSEGUIR EL RESTO DE VALOR(INT)/2, SI ES CERO ES PAR, SINO ES IMPAR.