CREATE TABLE CHALLENGE_3(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	FECHA DATE NOT NULL
)
--
INSERT INTO CHALLENGE_3(FECHA) VALUES ('1776'),('2001'),('1643'),('1865'),('1969')
--
SELECT	(YEAR(FECHA) + 100) / 100
FROM CHALLENGE_3
--
DROP TABLE CHALLENGE_3

-- SE UTILIZA TYPE(DATE) PARA NO LIMITAR LA TABLA SOLO A AÑOS Y SE TRABAJA CON YEAR().