CREATE TABLE FECHA_VTO(
	ID INT NOT NULL PRIMARY KEY,
	FECHA DATE NOT NULL
)
--
SET DATEFORMAT DMY
INSERT INTO FECHA_VTO(ID,FECHA) VALUES (1,'1-10-2023'),(2,'22-5-2025'),(5,'22-1-2023'),(6,'15-6-2028')
--
CREATE TABLE CHALLENGE_12(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_FECHAVTO INT,
	NOMBRE VARCHAR(30) NOT NULL,
	AGE INT NOT NULL CHECK(AGE>0)
)
--
INSERT INTO CHALLENGE_12(ID_FECHAVTO,NOMBRE,AGE) VALUES (1,'Bob',21),(1,'Sam',19),(2,'Jill',18),(3,'Jim',21),(4,'Sally',19),(2,'Jess',20),(3,'Will',21)
--
SELECT	C12.ID,
			C12.NOMBRE,
			C12.AGE,
			ISNULL(CONVERT(varchar,FECHA_VTO.FECHA,3),'')
FROM CHALLENGE_12 AS C12
LEFT JOIN FECHA_VTO ON FECHA_VTO.ID=C12.ID
--
DROP TABLE FECHA_VTO
DROP TABLE CHALLENGE_12

-- SE CONFIGURA EL FORMATO DE FECHAS DIAS, MES, AÑO. SE RESTRINGE AGE(INT) PARA MAYORES A CERO. SE UTILIZA ISNULL PARA DEJAR LA COLUMNA VACÍA EN CASO QUE NO ENCUENTRE FECHA. SE UTILIZA LEFT JOIN PARA VISUALIZAR TODOS LOS REGISTROS DE LA TABLA C12 INDISTINTO SI TIENE O NO FECHA_VTO.