CREATE TABLE CHALLENGE_5(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	AGE INT NOT NULL CHECK(AGE>0)
)
--
INSERT INTO CHALLENGE_5(NOMBRE,AGE) VALUES ('Bob',21),('Sam',19),('Jill',18),('Jim',21),('Sally',19),('Jess',20),('Will',21)--SELECT DISTINCT			AGE,			COUNT(AGE) AS 'COUNT'FROM CHALLENGE_5GROUP BY AGE--SE UTILIZA LA FUNCIÓN DE AGREGACIÓN COUNT() PARA CONTAR CUANTAS APARICIONES TIENE CADA EDAD.