CREATE TABLE CHALLENGE_9(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	AGE INT NOT NULL CHECK(AGE>0)
)
--
INSERT INTO CHALLENGE_9(NOMBRE,AGE) VALUES ('Bob',21),('Sam',19),('Jill',18),('Jim',21),('Sally',19),('Jess',20),('Will',21)
--
SELECT DISTINCT
			AGE
FROM CHALLENGE_9

--SE USA 'DISTINCT' PARA ELIMINAR DUPLICADOS EN LA CONSULTA.