CREATE TABLE CHALLENGE_1(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	VALOR INT NOT NULL
)
--
INSERT INTO CHALLENGE_1(VALOR) VALUES (-56),(76),(-84),(96),(-47)
--
SELECT	VALOR*-1
FROM CHALLENGE_1
--
DROP TABLE CHALLENGE_1

-- AL MULTIPLICAR EL VALOR(INT) POR -1 CAMBIARÁ SU SIGNO.