CREATE TABLE NATIONALITY(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DESCR VARCHAR(30) NOT NULL UNIQUE
)
--
INSERT INTO NATIONALITY(DESCR) VALUES ('Argentino'),('Italiano'),('Español'),('Aleman')
--
CREATE TABLE CHALLENGE_11(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_NATIONALITY INT NOT NULL FOREIGN KEY REFERENCES NATIONALITY(ID),
	NOMBRE VARCHAR(30) NOT NULL,
	AGE INT NOT NULL CHECK(AGE>0)
)
--
INSERT INTO CHALLENGE_11(ID_NATIONALITY,NOMBRE,AGE) VALUES (1,'Bob',21),(1,'Sam',19),(2,'Jill',18),(3,'Jim',21),(4,'Sally',19),(2,'Jess',20),(3,'Will',21)
--
SELECT	C11.ID,
			NATIONALITY.DESCR,
			C11.NOMBRE,
			C11.AGE
FROM CHALLENGE_11 AS C11
INNER JOIN NATIONALITY ON NATIONALITY.ID=C11.ID_NATIONALITY
--
DROP TABLE NATIONALITY
DROP TABLE CHALLENGE_11

-- SE RESTRINGE AGE(INT) PARA NUMERO POSITIVOS. SE CONECTAN LAS TABLAS POR INNER JOIN.