CREATE TABLE CHALLENGE_10(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	AGE INT NOT NULL CHECK(AGE>0)
)
--
INSERT INTO CHALLENGE_10(NOMBRE,AGE) VALUES ('Bob',21),('Sam',19),('Jill',18),('Jim',21),('Sally',19),('Jess',20),('Will',21)
--
SELECT	SUM(AGE)
FROM CHALLENGE_10
--
DROP TABLE CHALLENGE_10

-- SE UTILIZA LA FUNCION DE AGREGACIÓN SUM() PARA SUMAR LA COLUMNA AGE.